# Rutes for security of the system
dropmovi_frontend_login:
    pattern:  /login
    defaults: { _controller: DropmoviFrontendBundle:Security:login }
    
dropmovi_frontend_login_check:
    pattern:  /login_check
    
dropmovi_frontend_logout:
    pattern:  /logout
    
# URL protected
dropmovi_frontend_profile:
    pattern:  /user/profile
    defaults: { _controller: DropmoviFrontendBundle:Profile:profile }
    
dropmovi_frontend_configuration:
    pattern:  /user/configuration
    defaults: { _controller: DropmoviFrontendBundle:Configuration:configuration }
    
dropmovi_frontend_edit_profile:
    pattern:  /user/edit-profile
    defaults: { _controller: DropmoviFrontendBundle:Profile:editProfile }
    
dropmovi_frontend_new_publication:
    pattern:  /user/new-publication
    defaults: { _controller: DropmoviFrontendBundle:Publication:newPublication }
    
# URL public
dropmovi_frontend_homepage:
    pattern:  /
    defaults: { _controller: DropmoviFrontendBundle:Homepage:index }
    
dropmovi_frontend_signin:
    pattern:  /signin
    defaults: { _controller: DropmoviFrontendBundle:Signin:signin }
    
dropmovi_frontend_public_profile:
    pattern:  /{username}
    defaults: { _controller: DropmoviFrontendBundle:Profile:publicProfile }
    requirements:
        _method:  GET


    

