<?php

namespace Dropmovi\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository {

    public function addComment($comment, $user) {
        $em = $this->getEntityManager();
        $comment->setAuthor($user);
        $em->persist($comment);
        $em->flush();
    }

}
