<?php

namespace Dropmovi\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository {

    public function addComment($comment, $publication, $user) {
        $em = $this->getEntityManager();
        $comment->setPublication($publication);
        $comment->setAuthor($user);
        $em->persist($comment);
        $em->flush();
    }

    public function removeComment($id, $user) {
        $em = $this->getEntityManager();
        $comment = $em->find("DropmoviBackendBundle:Comment", $id);
        if ($user->getId() == $comment->getAuthor()->getId()) {
            $em->remove($comment);
            $em->flush();
        }
    }

}
